services:
  supplier-db:
    image: mysql:8.0
    container_name: simavek-supplier-db
    restart: always
    environment:
      MYSQL_DATABASE: supplier_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - supplier_db_data:/var/lib/mysql
    networks:
      - simavek-network

  supplier-service:
    build: ./simavek-supplier-service
    container_name: simavek-supplier-service
    restart: always
    depends_on:
      - supplier-db
      - rabbitmq
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: supplier-db
      DB_PORT: 3306
      DB_DATABASE: supplier_db
      DB_USERNAME: root
      DB_PASSWORD: root
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    networks:
      - simavek-network
